### ISSUE TITLE
Automatic calculation of matrices for state space models

### ISSUE THREAD

**Issue by sthebault** [locie/pySIP#4]
To code new dynamic models (such as RC network) it is not very straightforward to calculate and write all the matrices A, B, C, D and their derivatives respecting to the different parameters (dA, dB). It takes some time and there is a non-negligible risk of error.

The following notebook presents a conversion function that can be integrated to evaluate automatically the matrces in the "update_continuous_ssm" and "update_continuous_dssm" functions for each model, using only the continuous differential equations.

The example deals with the model twti_rorircawai

Works with sympy version >=1.4

[convert_equations_to_matrices_pySIP.pdf](https://github.com/locie/pySIP/files/3904257/convert_equations_to_matrices_pySIP.pdf)
(I can share with you the .ipynb file!)

**Comment by LoicRaillon** [comment]
Good initiative, thank you Simon !
I take advantage of this issue to post my solution, where you don't need to write the differential equations. I wrote a simple notebook (the method can be fully automated) to compute the state-space model and the jacobians of the model TwTi_RoRiAwAi.
The notebook is available [here](https://github.com/LoicRaillon/From-thermal-network-to-SSM/blob/master/rc_ss.ipynb)

**Comment by celliern** [comment]
Hello

This issue sould not be relevant in the next pySIP version : the code will be accelerated using numba and jacobian evaluated numerically, to reduce the amount of code to maintain.

This will de-facto remove the need for symbolic differentiation of the model.

If someone want to have the jacobian back, a promising lead is to rewrite the state space discretisation using pytensor, which will give access to the gradient using autograd methods.

I'm closing this issue for now, feel free to re-open it if you are interested in including autograd in the package
