### ISSUE TITLE
lambda (anonymous function) in code disallow correct pickling for multiprocess 

### ISSUE THREAD

**Issue by celliern** [locie/pySIP#5]
Hello !

I'm trying to run pySIP with a [distributed backend](git@github.com:celliern/pySIP.git)  which is compatible with `joblib`. I have gone through pickling error. On a local copy of pySIP, I noticed the presence of lambda function in the library core that lead to pickling errors.

I can do a pull request with extra tests to make pySIP more robust to pickling which should improve the compatibility with multiprocessing and distributed computation.

**Comment by mjanv** [comment]
Thanks for the update. Needs to check with the test suite, but the pull requests seems good.

**Comment by celliern** [comment]
Oh, I forgot to say that I ran pytest before doing the pull request!

Le dim. 2 févr. 2020 à 11:52, Maxime Janvier <notifications@github.com> a
écrit :

**Comment by LoicRaillon** [comment]
I did the update on the Gitlab which is a couple of commits  ahead of the Github. Everything is fine, we can push a new tag on the Github. We will be soon switching the development to the Github, thanks for the PR !
