### ISSUE TITLE
trying to use pySIP with raw field datas

### ISSUE THREAD

**Issue by alexandrecuer** [locie/pySIP#8]
Trying to use the  testpySIP.py file with my own datas,

[datas_ite_step1800s.zip](https://github.com/locie/pySIP/files/4325718/datas_ite_step1800s.zip)

![AllieHab_ITE](https://user-images.githubusercontent.com/24553739/76552119-f9ac2500-6493-11ea-8f18-695224f87b73.png)

tried with the following params:
```
parameters = [
    dict(name='Ro', scale=1e-2, transform='log'),
    dict(name='Ri', scale=1e-3, transform='log'),
    dict(name='Cw', scale=1e7 / sT, transform='log'),
    dict(name='Ci', scale=1e6 / sT, transform='log'),
    dict(name='sigw_w', scale=1e-2 * sT**0.5, transform='fixed'),
    dict(name='sigw_i', value=1e-2 * sT**0.5, transform='fixed'),
    dict(name='sigv', scale=1e-1, transform='log'),
    dict(name='x0_w', loc=21.0, transform='none'),
    dict(name='x0_i', value=22, transform='fixed'),
    dict(name='sigx0_w', value=0.1, transform='fixed'),
    dict(name='sigx0_i', value=0.1, transform='fixed'),
]
```
got this : 
```
Warning: Desired error not necessarily achieved due to precision loss.
         Current function value: 121.075823
         Iterations: 67
         Function evaluations: 159
         Gradient evaluations: 148

             θ      σ(θ)    pvalue    |g(η)|  |dpen(θ)|
Ro   2.684e-08 4.303e-06 9.950e-01 1.283e-04  1.388e-05
Ri   1.897e-03 6.222e-04 2.385e-03 1.926e-04  2.779e-17
Cw   4.645e+08 7.447e+10 9.950e-01 1.274e-04  6.209e-30
Ci   3.083e+02 1.196e+02 1.017e-02 1.990e-05  1.409e-19
sigv 2.352e-05 2.746e-03 9.932e-01 1.251e-06  1.808e-09
x0_w 1.684e+01 1.788e+00 0.000e+00 4.057e-05  0.000e+00
             Ro         Ri         Cw         Ci       sigv       x0_w
Ro    1.000e+00  9.074e-03 -1.000e+00 -7.330e-03  9.972e-01  1.330e-02
Ri    9.074e-03  1.000e+00 -8.487e-03 -6.613e-01 -1.731e-02 -6.531e-01
Cw   -1.000e+00 -8.487e-03  1.000e+00  7.165e-03 -9.972e-01 -1.441e-02
Ci   -7.330e-03 -6.613e-01  7.165e-03  1.000e+00  1.710e-02  2.154e-01
sigv  9.972e-01 -1.731e-02 -9.972e-01  1.710e-02  1.000e+00  4.101e-04
x0_w  1.330e-02 -6.531e-01 -1.441e-02  2.154e-01  4.101e-04  1.000e+00

```
![PySIP_w_smp1](https://user-images.githubusercontent.com/24553739/76597875-cef8b580-6501-11ea-826d-20497ab826a8.png)

Best 

Alex

**Comment by alexandrecuer** [comment]
with a different dataset of 5 days, things are going differently....
[datas_ite_step1800s_2.zip](https://github.com/locie/pySIP/files/4326470/datas_ite_step1800s_2.zip)

```
/home/alexandrecuer/pySIP/pysip/statespace/base.py:332: RuntimeWarning: invalid value encountered in matmul
  tmp = inv_Qd.T @ dQQd @ inv_Qd
/home/alexandrecuer/pySIP/pysip/statespace/base.py:332: RuntimeWarning: invalid value encountered in matmul
  tmp = inv_Qd.T @ dQQd @ inv_Qd
/home/alexandrecuer/pySIP/pysip/state_estimator/kalman_qr.py:115: RuntimeWarning: invalid value encountered in matmul
  dP = (np.swapaxes(np.tril(tmp, -1), 1, 2) + np.triu(tmp)) @ P
/home/alexandrecuer/pySIP/pysip/state_estimator/kalman_qr.py:115: RuntimeWarning: invalid value encountered in matmul
  dP = (np.swapaxes(np.tril(tmp, -1), 1, 2) + np.triu(tmp)) @ P
/home/alexandrecuer/pySIP/pysip/state_estimator/kalman_qr.py:115: RuntimeWarning: invalid value encountered in matmul
  dP = (np.swapaxes(np.tril(tmp, -1), 1, 2) + np.triu(tmp)) @ P
/home/alexandrecuer/pySIP/pysip/state_estimator/kalman_qr.py:115: RuntimeWarning: invalid value encountered in matmul
  dP = (np.swapaxes(np.tril(tmp, -1), 1, 2) + np.triu(tmp)) @ P
/home/alexandrecuer/pySIP/pysip/state_estimator/kalman_qr.py:115: RuntimeWarning: invalid value encountered in matmul
  dP = (np.swapaxes(np.tril(tmp, -1), 1, 2) + np.triu(tmp)) @ P
/home/alexandrecuer/pySIP/pysip/state_estimator/kalman_qr.py:115: RuntimeWarning: invalid value encountered in matmul
  dP = (np.swapaxes(np.tril(tmp, -1), 1, 2) + np.triu(tmp)) @ P
Warning: Desired error not necessarily achieved due to precision loss.
         Current function value: 1898.798725
         Iterations: 7
         Function evaluations: 66
         Gradient evaluations: 48

                θ      σ(θ)    pvalue    |g(η)|  |dpen(θ)|
Ro      3.887e-01 4.188e-01 3.544e-01 4.106e-05  6.620e-20
Ri      2.506e-03 3.179e-04 1.239e-13 1.397e+00  1.593e-17
Cw      3.024e+05 3.354e+05 3.682e-01 3.311e-01  1.465e-23
Ci      1.704e-01 1.927e-02 2.220e-16 6.212e+00  4.616e-13
sigw_w  8.533e+01 8.846e+00 0.000e+00 9.959e+01  1.187e-21
sigv    1.117e-08 6.006e-09 6.416e-02 7.482e-05  8.014e-05
x0_w   -1.187e+02 4.306e+00 2.000e+00 6.477e+00  0.000e+00
               Ro         Ri         Cw  ...     sigw_w       sigv       x0_w
Ro      1.000e+00 -7.192e-02  1.874e-01  ... -4.469e-01 -2.159e-01  4.373e-01
Ri     -7.192e-02  1.000e+00 -4.634e-01  ...  3.454e-01  8.811e-01 -6.585e-01
Cw      1.874e-01 -4.634e-01  1.000e+00  ... -6.779e-01 -5.258e-01  8.234e-01
Ci      1.722e-03 -9.395e-01  2.886e-01  ... -1.357e-01 -8.630e-01  5.460e-01
sigw_w -4.469e-01  3.454e-01 -6.779e-01  ...  1.000e+00  1.420e-01 -5.006e-01
sigv   -2.159e-01  8.811e-01 -5.258e-01  ...  1.420e-01  1.000e+00 -7.967e-01
x0_w    4.373e-01 -6.585e-01  8.234e-01  ... -5.006e-01 -7.967e-01  1.000e+00

[7 rows x 7 columns]
```
 
![AllieHab_ITE_2](https://user-images.githubusercontent.com/24553739/76565407-cf199680-64aa-11ea-88ad-ec8ffd195598.png)

![PySIP_w_smp2](https://user-images.githubusercontent.com/24553739/76565463-ea84a180-64aa-11ea-935d-61eaefd4fdd6.png)

**Comment by LoicRaillon** [comment]
Hi Alexandre,

I played a little bit with your second data set and it seems that you don't have enough excitation in your data to fit a reliable model.
Do you have any pySIP related questions?

**Comment by alexandrecuer** [comment]
Hello,

thanks for your answer :-)

both sets are coming from the same building, during the same winter season, so the model adjusted for set 1 should work for set 2, but I tried an optimization with set 2 just to see how things were going :-)

I've seen the following notebook which explains some things about RC model calibration
https://github.com/srouchier/InverseBuilding/blob/master/04_RC_Box/04_RC.ipynb''`

I suppose this article to be the basis on which pySIP is developed
the discretisation scheme is in the RC_model_deterministic predict function : 

```
def RC_model_deterministic(u, R1, R2, C1, C2, k1, k2, xe_0):
    
    # Matrices of the system in continuous form
    Ac = np.array([[-1/(C1*R1)-1/(C1*R2), 1/(C1*R2)],
                   [1/(C2*R2), -1/(C2*R2)]])
    Bc = np.array([[1/(C1*R1), 0, k1/C1],
                   [0, 1/C2, k2/C2]])
    n = 2   # number of states
    # Matrices of the discretized state-space model
    F = expm(Ac*delta_t)
    G = dot3(inv(Ac), F-np.eye(n), Bc)
    H = np.array([[0, 1]])
    
    # Initialisation of the states
    x = np.zeros((len(u), n))
    x[0] = np.array((xe_0, T_in[0]))
    
    # Simulation
    for i in range(1,len(u)):
        x[i] = np.dot(F, x[i-1]) + np.dot(G, u[i-1])
```

is it more precise than a classic Euler implicit scheme ?

Coming back to the general problem, I'm not sure what to think of an optimization with unregulated parameters. The resistances are close to 1e-2 or 1e-3 and the capacities are close to 1e6, 1e7 or even 1e8...do you practice a regularization in pySIP ? 

 I've tested my own algorithm, without regularization, giving the functional to minimize and its gradient to scipy 'minimize' with a BFGS algorithm....anyway, I must admit these datasets come from individual houses, with very few periods of innocupation....  

do yu think model optimized by pySIP with set 1 is reliable ?

best

Alex

**Comment by LoicRaillon** [comment]
Hi,

> is it more precise than a classic Euler implicit scheme ?

The discretization is exact in pySIP (a closed-form solution exists for linear Gaussian SDE) and more precise than the implicit Euler scheme, which is an approximation.

> Coming back to the general problem, I'm not sure what to think of an optimization with unregulated parameters. The resistances are close to 1e-2 or 1e-3 and the capacities are close to 1e6, 1e7 or even 1e8...do you practice a regularization in pySIP ?

I think you're confusing regularization and scaling. You can scale you parameters individually, see the documentation for more information [https://locie.github.io/pySIP/core/parameter.html](url).

> do yu think model optimized by pySIP with set 1 is reliable ?

Did the optimization succeed? All parameters are statistically significant and not close to the bounds? Did you check the residuals, auto/cross-correlation, cumulated periodogram? 

Loïc

**Comment by alexandrecuer** [comment]
>I think you're confusing regularization and scaling. You can scale you parameters individually, see the documentation for more information https://locie.github.io/pySIP/core/parameter.html.

good point, I've just understood...

>The discretization is exact in pySIP (a closed-form solution exists for linear Gaussian SDE) and more precise than the implicit Euler scheme, which is an approximation.

I just wrote this and for me there is an approximation in the second term but probably I am misunderstanding something:

https://github.com/alexandrecuer/tf_works/blob/master/BIOS/RC/dis_scheme.ipynb
https://github.com/alexandrecuer/tf_works/blob/master/BIOS/RC/dis_scheme.pdf

> Did the optimization succeed? All parameters are statistically significant and not close to the bounds? Did you check the residuals, auto/cross-correlation, cumulated periodogram?

OK going to investigate auto/cross-correlation.....
do yu think a resistance close to 1e2 is something realistic ? I am working with a R3C2 model and the resistance close to 1e2 after optimization is the outdoor thermal resistance of walls....

**Comment by LoicRaillon** [comment]
> I just wrote this and for me there is an approximation in the second term but probably I am misunderstanding something:
https://github.com/alexandrecuer/tf_works/blob/master/BIOS/RC/dis_scheme.ipynb
https://github.com/alexandrecuer/tf_works/blob/master/BIOS/RC/dis_scheme.pdf

Your last equation is exactly 
```
F = expm(Ac*delta_t) 
G = dot3(inv(Ac), F-np.eye(n), Bc)
```
This is the solution to Linear Time Invariant state-space models that you can easily find online.
